// Generates src/version.ts from package.json so the published code always
// reports its true version. Runs as part of `npm run build`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
writeFileSync(
  join(root, "src/version.ts"),
  `// Generated by scripts/gen-version.mjs — do not edit.\nexport const VERSION = "${version}";\n`,
);
console.log(`version.ts → ${version}`);
